# Random Numbers

***

## Prequisites

***

https://numpy.org/doc/stable/reference/random/index.html

In [1]:
# Numerical arrays and random numbers.
import numpy as np

In [4]:
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()  

0.006096473283986548

In [5]:
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10) 

array([-5.29689998e-01, -9.97379225e-04, -3.33210771e-01,  2.82627404e-01,
        2.67995125e+00,  5.24626371e-01, -1.82052778e-02,  6.37743758e-01,
       -1.32314429e+00, -6.37623912e-01])

In [6]:
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5) 

array([6, 4, 1, 7, 7])

## Generate Random Integers
***

In [2]:
rng = np.random.default_rng()
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()  
0.06369197489564249  # may vary
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10)  
array([-0.31018314, -1.8922078 , -0.3628523 , -0.63526532,  0.43181166,  # may vary
        0.51640373,  1.25693945,  0.07779185,  0.84090247, -2.13406828])
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5)  
array([8, 7, 6, 2, 0])  # may vary

NameError: name 'array' is not defined

In [3]:
rng = np.random.default_rng()